package net.theevilreaper.vulpes.generator.generation.doc

/**
 * The interface hold some method to generate class documentation header for a generated class.
 * @author theEvilReaper
 * @version 1.0.0
 * @since 1.0.0
 */
interface ClassDocumentation {
    /**
     * Returns a pre define string for the documentation header of a class.
     * @return the pre-defined string
     */
    val defaultDocumentation: String
        get() = """
            Don't edit this file because it's auto generated.
            Each change will be overwritten when the files gets generated by the generator.
            
            @author $authorTag
            @version $versionTag
            @since $sinceTag
            """.trimIndent()

    /**
     * Returns the author for the documentation tag.
     * @return the given author value
     */
    val authorTag: String
        get() = "System"

    /**
     * Returns the version for the documentation tag.
     * @return the given version value
     */
    val versionTag: String
        get() = "1.0.0"

    /**
     * Returns the since (version) for the documentation tag.
     * @return the given since value
     */
    val sinceTag: String
        get() = "1.0.0"
}