micronaut:
  application:
    name: vulpes-generator
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

# Git configuration
git:
  repo:
    url: https://github.com/yourusername/your-repo.git
  commit:
    author: Vulpes Generator <generator@onelitefeather.net>

# Logging configuration
logger:
  levels:
    net.onelitefeather.vulpes: INFO
    io.micronaut: INFO