micronaut:
  server:
    port: ${PORT:8080}
  application:
    name: Vulpes Generator
  logger:
    level:
      io.micronaut: DEBUG
mongodb:
  uri: mongodb://localhost:27017
  database: test

commit:
  commitName: "Vulpes"
  commitMail: "vulpes@onelitefeather.com"
  defaultMessage: "Initial commit"
