services:
  mariadb_vulpes:
    image: mariadb:latest
    container_name: mariadb_vulpes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vulpes
      MYSQL_DATABASE: vulpes
    ports:
      - "3336:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql