# docker compose up -d
services:
  postgres:
    image: postgres:16
    container_name: 'postgres_vulpes'
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: vulpes
      POSTGRES_DB: vulpes
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    networks:
      - vulpes_go_net
networks:
  vulpes_go_net:
    driver: bridge
